version: "3.7"

services:

  rs1:
    image: mongo:4.2.5
    volumes:
      - fisiohubdb1:/data/db
    ports:
      - 27017:27017
    command: --replSet replSet

  rs2:
    image: mongo:4.2.5
    volumes:
      - fisiohubdb2:/data/db
    command: --replSet replSet

  rs3:
    image: mongo:4.2.5
    volumes:
      - fisiohubdb3:/data/db
    command: --replSet replSet

  server:
    image: node:12.16.1
    command: sh -c "yarn wait-port rs1:27017 && yarn dev"
    working_dir: /fisio-hub
    volumes:
      - ./:/fisio-hub
    environment:
      DB_URI: "mongodb://rs1,rs2,rs3/?replicaSet=replSet"
      DB_URI_ADMIN: "mongodb://rs1,rs2,rs3/?replicaSet=replSet"
    ports:
      - 3000:3000
    
volumes: 
  fisiohubdb1:
  fisiohubdb2:
  fisiohubdb3: